name = "LinearTransforms"
uuid = "dc8ba9e7-38a5-4c48-a973-b3558fbf1cda"
authors = ["Michael Friedlander <michael@friedlander.io>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
